

import { Vehicle, VehicleType, FuelType, Showroom } from './types';

export const VEHICLES: Vehicle[] = [
  {
    id: 1,
    name: 'Splendor Plus',
    brand: 'Hero',
    price: 75000,
    type: VehicleType.BIKE,
    fuelType: FuelType.PETROL,
    imageUrl: 'https://imgd.aeplcdn.com/664x374/n/cw/ec/1/versions/--drum-obd-2b1744868494481.jpg?q=80',
    mileage: '65 kmpl',
    engine: '97.2 cc',
    power: '8.02 PS',
    brakes: 'Drum',
    description: 'The Hero Splendor Plus is one of the most popular and reliable commuter bikes in India, known for its fuel efficiency and low maintenance cost.',
    specs: { 'Engine Type': 'Air cooled, 4-stroke, single cylinder', 'Displacement': '97.2 cc', 'Max Power': '8.02 PS @ 8000 rpm', 'Fuel Capacity': '9.8 L' },
    rating: 4.5,
    reviews: [
      { id: 1, userName: 'Ravi', rating: 5, comment: 'Best mileage bike, very reliable for daily use.', date: '2023-10-15' },
      { id: 2, userName: 'Sunita', rating: 4, comment: 'Good bike but the design is a bit old.', date: '2023-09-22' },
    ],
  },
  {
    id: 2,
    name: 'Activa 6G',
    brand: 'Honda',
    price: 80000,
    type: VehicleType.SCOOTER,
    fuelType: FuelType.PETROL,
    imageUrl: 'https://etimg.etb2bimg.com/thumb/msid-73268968,width-1200,height-900,resizemode-4/.jpg',
    mileage: '50 kmpl',
    engine: '109.51 cc',
    power: '7.79 PS',
    brakes: 'Drum',
    description: 'The Honda Activa 6G is the quintessential Indian scooter, offering a perfect blend of performance, comfort, and reliability for city commutes.',
    specs: { 'Engine Type': 'Fan Cooled, 4 Stroke, SI Engine', 'Displacement': '109.51 cc', 'Max Power': '7.79 PS @ 8000 rpm', 'Fuel Capacity': '5.3 L' },
    rating: 4.7,
    reviews: [
      { id: 3, userName: 'Amit', rating: 5, comment: 'Smooth engine and very comfortable to ride.', date: '2023-11-01' },
      { id: 4, userName: 'Priya', rating: 4, comment: 'Great scooter, but could use a front disc brake.', date: '2023-10-18' },
    ],
  },
  {
    id: 3,
    name: 'Pulsar NS200',
    brand: 'Bajaj',
    price: 150000,
    type: VehicleType.BIKE,
    fuelType: FuelType.PETROL,
    imageUrl: 'https://imgd.aeplcdn.com/1280x720/n/bw/models/colors/bajaj-select-model-pewter-grey-1709101653302.png',
    mileage: '35 kmpl',
    engine: '199.5 cc',
    power: '24.5 PS',
    brakes: 'Disc',
    description: 'The Bajaj Pulsar NS200 is a performance-oriented street bike that boasts aggressive styling, a powerful engine, and nimble handling.',
    specs: { 'Engine Type': 'Liquid Cooled, Triple Spark, 4-Valve FI DTS-i', 'Displacement': '199.5 cc', 'Max Power': '24.5 PS @ 9750 rpm', 'Fuel Capacity': '12 L' },
    rating: 4.6,
    reviews: [
      { id: 5, userName: 'Vikram', rating: 5, comment: 'Amazing performance for the price!', date: '2024-01-10' },
    ],
  },
  {
    id: 4,
    name: 'Ather 450X',
    brand: 'Ather',
    price: 160000,
    type: VehicleType.SCOOTER,
    fuelType: FuelType.ELECTRIC,
    imageUrl: 'https://etimg.etb2bimg.com/photo/106592360.cms',
    mileage: '110 km/charge',
    engine: '6.4 kW PMSM Motor',
    power: '8.7 PS',
    brakes: 'Disc',
    description: 'The Ather 450X is a premium electric scooter that sets the benchmark for performance and smart features, including a touchscreen dashboard and OTA updates.',
    specs: { 'Motor Type': 'PMSM', 'Range': '110 km (Eco Mode)', 'Charging Time': '5 hr 40 min', 'Battery Capacity': '3.7 kWh' },
    rating: 4.8,
    reviews: [
        { id: 6, userName: 'Neha', rating: 5, comment: 'The future of scooters is here. Amazing tech!', date: '2024-02-20' },
        { id: 7, userName: 'Karan', rating: 4, comment: 'A bit pricey but worth it for the features.', date: '2024-02-15' },
    ],
  },
  {
    id: 5,
    name: 'Classic 350',
    brand: 'Royal Enfield',
    price: 220000,
    type: VehicleType.BIKE,
    fuelType: FuelType.PETROL,
    imageUrl: 'https://imgd.aeplcdn.com/1280x720/n/cw/ec/183389/classic-350-right-side-view-62.jpeg?isig=0&q=100',
    mileage: '37 kmpl',
    engine: '349 cc',
    power: '20.2 PS',
    brakes: 'Disc',
    description: 'The Royal Enfield Classic 350 is an iconic cruiser with a timeless design, offering a comfortable ride and the signature thump that riders love.',
    specs: { 'Engine Type': 'Single cylinder, 4 stroke, Air-Oil cooled', 'Displacement': '349.34 cc', 'Max Power': '20.2 PS @ 6100 rpm', 'Fuel Capacity': '13 L' },
    rating: 4.7,
    reviews: [
        { id: 8, userName: 'Rajesh', rating: 5, comment: 'Nothing beats the feeling of riding a Classic 350.', date: '2023-12-05' },
    ],
  },
  {
    id: 6,
    name: 'Ola S1 Pro',
    brand: 'Ola',
    price: 130000,
    type: VehicleType.SCOOTER,
    fuelType: FuelType.ELECTRIC,
    imageUrl: 'https://gaadiwaadi.com/wp-content/uploads/2024/12/Ola-S1-Pro-Sona-2.jpg',
    mileage: '170 km/charge',
    engine: '5.5 kW Mid Drive IPM',
    power: '11.5 PS',
    brakes: 'Disc',
    description: 'The Ola S1 Pro disrupts the EV market with its long range, powerful motor, and a host of tech features, all packed in a sleek, modern design.',
    specs: { 'Motor Type': 'Mid Drive IPM', 'Range': '170 km (Eco Mode)', 'Top Speed': '120 kmph', 'Battery Capacity': '4 kWh' },
    rating: 4.3,
    reviews: [
      { id: 9, userName: 'Deepa', rating: 4, comment: 'Excellent range but the software has some bugs.', date: '2024-01-25' },
    ],
  },
   {
    id: 7,
    name: 'TVS Raider 125',
    brand: 'TVS',
    price: 95000,
    type: VehicleType.BIKE,
    fuelType: FuelType.PETROL,
    imageUrl: 'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcQMtuEINNDADY4QAnko_ndIqEH_QUQdLPgTtg&s',
    mileage: '57 kmpl',
    engine: '124.8 cc',
    power: '11.38 PS',
    brakes: 'Disc',
    description: 'The TVS Raider 125 is a sporty commuter bike with a striking design, digital console, and a peppy engine that offers a fun riding experience.',
    specs: { 'Engine Type': 'Air and oil cooled single cylinder, SI', 'Displacement': '124.8 cc', 'Max Power': '11.38 PS @ 7500 rpm', 'Fuel Capacity': '10 L' },
    rating: 4.6,
    reviews: [],
  },
  {
    id: 8,
    name: 'Jupiter 125',
    brand: 'TVS',
    price: 88000,
    type: VehicleType.SCOOTER,
    fuelType: FuelType.PETROL,
    imageUrl: 'https://www.tvsmotor.com/tvs-jupiter-125/~/media/TVS%20Jupiter%20125/Disc/Locate%20Dealer/Disc%20Jupiter_Range-393x326.webp',
    mileage: '50 kmpl',
    engine: '124.8 cc',
    power: '8.15 PS',
    brakes: 'Drum',
    description: 'The TVS Jupiter 125 is a practical and spacious scooter with the largest underseat storage in its class and an external fuel filler cap for convenience.',
    specs: { 'Engine Type': 'Single cylinder, 4 stroke, CVTi, fuel injection', 'Displacement': '124.8 cc', 'Max Power': '8.15 PS @ 6500 rpm', 'Fuel Capacity': '5.1 L' },
    rating: 4.5,
    reviews: [],
  },
  {
    id: 9,
    name: 'MT-15 Version 2.0',
    brand: 'Yamaha',
    price: 170000,
    type: VehicleType.BIKE,
    fuelType: FuelType.PETROL,
    imageUrl: 'https://cdn.bikedekho.com/processedimages/yamaha/mt-15-2-0/source/mt-15-2-06613f885e681c.jpg',
    mileage: '48 kmpl',
    engine: '155 cc',
    power: '18.4 PS',
    brakes: 'Disc',
    description: 'With its aggressive styling and a potent 155cc liquid-cooled engine, the Yamaha MT-15 offers a thrilling ride for the urban warrior.',
    specs: { 'Engine Type': 'Liquid cooled, 4-stroke, SOHC, 4-valve', 'Displacement': '155 cc', 'Max Power': '18.4 PS @ 10000 rpm', 'Fuel Capacity': '10 L' },
    rating: 4.8,
    reviews: [],
  },
  {
    id: 10,
    name: '390 Duke',
    brand: 'KTM',
    price: 310000,
    type: VehicleType.BIKE,
    fuelType: FuelType.PETROL,
    imageUrl: 'https://cdn.bikedekho.com/processedimages/ktm/2021-390-duke/source/2021-390-duke67d19c0d0c17b.jpg?imwidth=412&impolicy=resize',
    mileage: '28 kmpl',
    engine: '399 cc',
    power: '46 PS',
    brakes: 'Disc',
    description: 'The KTM 390 Duke is the ultimate corner rocket, boasting a lightweight chassis, powerful engine, and a suite of electronics for an exhilarating experience.',
    specs: { 'Engine Type': 'Single Cylinder, Liquid Cooled, DOHC', 'Displacement': '399 cc', 'Max Power': '46 PS @ 8500 rpm', 'Fuel Capacity': '15 L' },
    rating: 4.9,
    reviews: [],
  },
  {
    id: 11,
    name: 'Hness CB350',
    brand: 'Honda',
    price: 210000,
    type: VehicleType.BIKE,
    fuelType: FuelType.PETROL,
    imageUrl: 'https://cdn.prod.website-files.com/619e376b8bd48359093e2b50/683984b5e94beb82ed8c1497_dlx%20pro%20chrome%20variant%203.webp',
    mileage: '45 kmpl',
    engine: '348.36 cc',
    power: '21.07 PS',
    brakes: 'Disc',
    description: 'A modern classic, the Honda H\'ness CB350 combines timeless design with modern features and a refined, torquey engine for a majestic ride.',
    specs: { 'Engine Type': '4 Stroke, SI Engine', 'Displacement': '348.36 cc', 'Max Power': '21.07 PS @ 5500 rpm', 'Fuel Capacity': '15 L' },
    rating: 4.7,
    reviews: [],
  },
  {
    id: 12,
    name: 'Apache RTR 160 4V',
    brand: 'TVS',
    price: 125000,
    type: VehicleType.BIKE,
    fuelType: FuelType.PETROL,
    imageUrl: 'https://imgd.aeplcdn.com/1056x594/n/bw/models/colors/tvs-select-model-lightning-blue-1702974845209.png?q=80',
    mileage: '45 kmpl',
    engine: '159.7 cc',
    power: '17.55 PS',
    brakes: 'Disc',
    description: 'The TVS Apache RTR 160 4V is a race-bred machine for the streets, offering sharp handling, a rev-happy engine, and sporty ergonomics.',
    specs: { 'Engine Type': 'SI, 4 stroke, Oil cooled, SOHC, Fi', 'Displacement': '159.7 cc', 'Max Power': '17.55 PS @ 9250 rpm', 'Fuel Capacity': '12 L' },
    rating: 4.6,
    reviews: [],
  },
  {
    id: 13,
    name: 'Sprint Pro',
    brand: 'Hero',
    price: 15000,
    type: VehicleType.BICYCLE,
    fuelType: FuelType.MANUAL,
    imageUrl: 'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcRsYAkjsEXzc2yB1Ff7AXavAE7FXjLddVugmQ&s',
    mileage: 'Human Powered',
    engine: 'N/A',
    power: 'N/A',
    brakes: 'Disc',
    description: 'The Hero Sprint Pro is a robust mountain bike designed for off-road trails, featuring front suspension and dual disc brakes for superior control.',
    specs: { 'Frame': 'Alloy', 'Gears': '21-Speed Shimano', 'Suspension': 'Front', 'Brakes': 'Dual Disc' },
    rating: 4.2,
    reviews: [],
  },
  {
    id: 14,
    name: 'Riverside 120',
    brand: 'Btwin',
    price: 12000,
    type: VehicleType.BICYCLE,
    fuelType: FuelType.MANUAL,
    imageUrl: 'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcTG5jJBId0ZdddVWwIW--iEByhiAtFf5UkmFw&s',
    mileage: 'Human Powered',
    engine: 'N/A',
    power: 'N/A',
    brakes: 'V-Brake',
    description: 'A versatile hybrid cycle from Decathlon\'s Btwin, perfect for both city commuting and weekend rides on country paths. Simple and efficient.',
    specs: { 'Frame': 'Steel', 'Gears': '8-Speed Microshift', 'Suspension': 'None', 'Brakes': 'V-Brakes' },
    rating: 4.4,
    reviews: [],
  },
  {
    id: 15,
    name: 'Road Runner Pro D',
    brand: 'Firefox',
    price: 25000,
    type: VehicleType.BICYCLE,
    fuelType: FuelType.MANUAL,
    imageUrl: 'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcQ0TZRASbrkZTR2vzozjTbLRVHlYK83xPUOHg&s',
    mileage: 'Human Powered',
    engine: 'N/A',
    power: 'N/A',
    brakes: 'Disc',
    description: 'The Firefox Road Runner is a lightweight road bike built for speed and efficiency, featuring a sleek alloy frame and responsive disc brakes.',
    specs: { 'Frame': 'Alloy Hybrid', 'Gears': '14-Speed Shimano', 'Suspension': 'None', 'Brakes': 'Mechanical Disc' },
    rating: 4.5,
    reviews: [],
  },
  {
    id: 16,
    name: 'Marlin 5',
    brand: 'Trek',
    price: 45000,
    type: VehicleType.BICYCLE,
    fuelType: FuelType.MANUAL,
    imageUrl: 'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcTV_YbD5NXmEp05o4QE9rw1aFjJt0RtlzHQKQ&s',
    mileage: 'Human Powered',
    engine: 'N/A',
    power: 'N/A',
    brakes: 'Disc',
    description: 'A trail-worthy daily rider that\'s perfectly suited for everyday adventures, on and off the trail. Features a suspension fork and a 2x8 drivetrain.',
    specs: { 'Frame': 'Alpha Silver Aluminum', 'Gears': '16-Speed Shimano', 'Suspension': 'SR Suntour XCT 30', 'Brakes': 'Hydraulic Disc' },
    rating: 4.8,
    reviews: [],
  },
  {
    id: 17,
    name: 'Passion Pro',
    brand: 'Hero',
    price: 85000,
    type: VehicleType.BIKE,
    fuelType: FuelType.PETROL,
    imageUrl: 'https://www.otocapital.in/_next/image?url=https%3A%2F%2Fassets.otocapital.in%2Fprod%2Fblack-with-frost-blue-hero-passionpro-image.jpeg&w=1536&q=75',
    mileage: '70 kmpl',
    engine: '113.2 cc',
    power: '9.15 PS',
    brakes: 'Drum',
    description: 'The Hero Passion Pro is a stylish commuter bike that offers a great blend of mileage, performance, and features.',
    specs: { 'Engine Type': 'Air cooled, 4-stroke', 'Displacement': '113.2 cc', 'Max Power': '9.15 PS @ 7500 rpm', 'Fuel Capacity': '10 L' },
    rating: 4.4,
    reviews: [],
  },
  {
    id: 18,
    name: 'Glamour XTEC',
    brand: 'Hero',
    price: 88000,
    type: VehicleType.BIKE,
    fuelType: FuelType.PETROL,
    imageUrl: 'https://imgd.aeplcdn.com/1056x594/n/bw/models/colors/hero-select-model-black-1707130685273.png?q=80',
    mileage: '60 kmpl',
    engine: '124.7 cc',
    power: '10.84 PS',
    brakes: 'Disc',
    description: 'The Hero Glamour XTEC is a feature-packed commuter with a digital console, Bluetooth connectivity, and a refined engine.',
    specs: { 'Engine Type': 'Air cooled, 4-stroke', 'Displacement': '124.7 cc', 'Max Power': '10.84 PS @ 7500 rpm', 'Fuel Capacity': '10 L' },
    rating: 4.5,
    reviews: [],
  },
  {
    id: 19,
    name: 'Apache RR 310',
    brand: 'TVS',
    price: 272000,
    type: VehicleType.BIKE,
    fuelType: FuelType.PETROL,
    imageUrl: 'https://images.drivespark.com/img/2024/09/2024-tvs-apache-rr-310-review-front-view-1727416796.jpg',
    mileage: '30 kmpl',
    engine: '312.2 cc',
    power: '34 PS',
    brakes: 'Disc',
    description: 'Born on the racetrack, the TVS Apache RR 310 is a supersport bike that offers cutting-edge technology, sharp handling, and thrilling performance.',
    specs: { 'Engine Type': 'SI, 4 stroke, 4 valve, Single cylinder, Liquid cooled, Reverse inclined', 'Displacement': '312.2 cc', 'Max Power': '34 PS @ 9700 rpm', 'Fuel Capacity': '11 L' },
    rating: 4.8,
    reviews: [],
  },
  {
    id: 20,
    name: '42',
    brand: 'Jawa',
    price: 198000,
    type: VehicleType.BIKE,
    fuelType: FuelType.PETROL,
    imageUrl: 'https://m.otocapital.in/_next/image?url=https%3A%2F%2Fassets.otocapital.in%2Fproduction%2Fnew-jawa-perak-unveiled-with-stealth-edition.png&w=1024&q=75',
    mileage: '33 kmpl',
    engine: '294.72 cc',
    power: '27.33 PS',
    brakes: 'Disc',
    description: 'The Jawa 42 is a modern classic that blends retro styling with a powerful liquid-cooled engine, offering a unique and spirited riding experience.',
    specs: { 'Engine Type': 'Single Cylinder, 4 Stroke, Liquid Cooled, DOHC', 'Displacement': '294.72 cc', 'Max Power': '27.33 PS', 'Fuel Capacity': '13.2 L' },
    rating: 4.6,
    reviews: [],
  },
  {
    id: 21,
    name: 'Access 125',
    brand: 'Suzuki',
    price: 82000,
    type: VehicleType.SCOOTER,
    fuelType: FuelType.PETROL,
    imageUrl: 'https://cdn.suzukimotorcycle.co.in/public-live/uploads/color-images/original/370-01-2025-Suzuki-Access-Website_Absolute-Side_620x428pix-01.png',
    mileage: '52 kmpl',
    engine: '124 cc',
    power: '8.7 PS',
    brakes: 'Disc',
    description: 'The Suzuki Access 125 is a popular family scooter known for its refined engine, comfortable ride, and practical features like external fuel filling.',
    specs: { 'Engine Type': '4-Stroke, 1-Cylinder, Air Cooled', 'Displacement': '124 cc', 'Max Power': '8.7 PS @ 6750 rpm', 'Fuel Capacity': '5 L' },
    rating: 4.7,
    reviews: [],
  }
];

export const UPCOMING_VEHICLES: (Pick<Vehicle, 'name' | 'brand' | 'imageUrl' | 'description'> & { launchDate: string })[] = [
    {
        name: 'Electric Pulsar',
        brand: 'Bajaj',
        imageUrl: 'https://www.motorbeam.com/wp-content/uploads/Husqvarna-E-Pilen-Concept.jpg',
        description: 'Bajaj is rumored to be electrifying its iconic Pulsar brand, promising thrilling performance in a silent, eco-friendly package.',
        launchDate: 'December 2025',
    },
    {
        name: 'Activa Electric',
        brand: 'Honda',
        imageUrl: 'https://c.ndtvimg.com/2024-11/hmhqlkqo_honda-cuv-e_625x300_26_November_24.jpg?im=FeatureCrop,algorithm=dnn,width=1200,height=738',
        description: 'Honda\'s much-anticipated entry into the EV space. Expected to combine Activa\'s reliability with modern electric technology.',
        launchDate: 'January 2026',
    }
];

export const SHOWROOMS: Showroom[] = [
  { id: 1, name: 'Capital Honda', address: 'GNT Road, Opp. RTC Bus Stand', city: 'Ongole', phone: '9876543210', lat: 15.507, lng: 80.045 },
  { id: 2, name: 'Advaith Bajaj', address: '6-254, Kurnool Road, Santhapeta', city: 'Ongole', phone: '9876543211', lat: 15.505, lng: 80.040 },
  { id: 3, name: 'Vayu Ather Space', address: 'Beside Capital Honda, Grand Trunk Road', city: 'Ongole', phone: '9876543212', lat: 15.507, lng: 80.046 },
  { id: 4, name: 'Ace Royal Enfield', address: 'Plot no 57, Industrial Estate, Kurnool Rd', city: 'Ongole', phone: '9876543213', lat: 15.498, lng: 80.035 },
  { id: 5, name: 'Deccan Honda', address: '55, MG Road', city: 'Vijayawada', phone: '9123456780', lat: 16.50, lng: 80.64 },
  { id: 6, name: 'Sai Service Bajaj', address: '77, Eluru Road', city: 'Vijayawada', phone: '9123456781', lat: 16.51, lng: 80.65 },
];